/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockedPrecompileSol from "./MockedPrecompile.sol";
export type { mockedPrecompileSol };
export type { ACL } from "./ACL";
