/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IACL,
  IACLInterface,
} from "../../../../contracts/test/MockedPrecompile.sol/IACL";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "handle",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "allowTransient",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IACL__factory {
  static readonly abi = _abi;
  static createInterface(): IACLInterface {
    return new Interface(_abi) as IACLInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IACL {
    return new Contract(address, _abi, runner) as unknown as IACL;
  }
}
